### ISSUE TITLE
Intercom banner doesn't disappear after pausing it

### ISSUE THREAD

**Issue by ritute** [devrnt/react-use-intercom#605] opened 2023-01-19 22:47 UTC
**Describe the bug**
We are using this to display Intercom banners in our app. However, we noticed that whenever we enable a new banner, we have to reload our app in order to display it (have found out a way around this by calling update() on an interval to fetch the update). But, if we pause the banner, it doesn't disappear unless we reload the app. We're using manual boot.

**To Reproduce**

**Codesandbox link**
Include a codesandox will help us to investigate the issue quicker.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrnt** [comment] 2023-01-29 12:35
Please provide a reproduction in CodeSandbox or Stackblitz

**Comment by ritute** [comment] 2023-02-02 15:19
> 

Don't think that would work - you need access to intercom to enable & then pause a banner. You can try a simple example, create a banner, set it live, then pause it.

**Comment by devrnt** [comment] 2023-03-12 09:43
Closing because there is no reproduction, feel free to re-open with a reproduction

**Closed by devrnt** 2023-03-12 09:43 UTC
