### ISSUE TITLE
Lost style from material UI

### ISSUE THREAD

**Issue by taiducnguyen** [devrnt/react-use-intercom#514] opened 2022-08-05 10:28 UTC
Hi,

I'm using `nextjs `and trying to integrate with `intercom` then I found the issue:
When opening the chat box and then clicking on the close button, the material UI style is lost
![image](https://user-images.githubusercontent.com/22149480/183058112-a6f6ee01-3f2d-4f59-9aa4-201cafe52af5.png)
And I also see another error when I go to the other navigation page:
![image](https://user-images.githubusercontent.com/22149480/183058743-323c6e51-635f-4ff6-b1b5-bb9f9c75565c.png)

![image](https://user-images.githubusercontent.com/22149480/183058503-358795ee-feae-471c-8b51-c03146d48331.png)

Do you guys have any idea about this issue ?

**Comment by ferpintado** [comment] 2022-08-12 00:07
same problem here https://streamable.com/we89py

**Comment by devrnt** [comment] 2022-08-29 05:48
Hi, thanks for creating this issue.

Can you provide a reproduction?

**Comment by ferpintado** [comment] 2022-08-31 02:11
> Hi, thanks for creating this issue.
> 
> Can you provide a reproduction?

```
...
...
const { show, update } = useIntercom();
...
...
<Button
  endIcon={<HelpOutline />}
  variant="text"
  onClick={show}
>
  Ayuda
</Button>

 ```

dependencies:

"@emotion/react": "^11.7.1",
"@emotion/server": "^11.4.0",
"@emotion/styled": "^11.6.0",
"@mui/material": "^5.3.1",
"next": "12.1.0",
"react": "17.0.2",

1.- Open your app in mobile size window
2.- Click on the button

Intercom would open fine

3.-Close intercom
4.- Navigate to another route

App styling is broken

**Comment by devrnt** [comment] 2022-09-19 18:10
Could you provide a codesandbox/stackblitz link with a small reproduction?

**Comment by devrnt** [comment] 2022-10-05 17:59
Feel free to re-open

**Comment by rspauwen** [comment] 2022-10-13 11:25
Hi, I'm having the same issue with next.js and only on mobile

**Comment by rspauwen** [comment] 2022-12-29 08:06
> Feel free to re-open

I'd like to re-open it, but don't know how...

**Comment by WolfH** [comment] 2023-01-16 18:36
Hi @devrnt, we're not able to manually reopen this ticket ourselves. Could you reopen it?

**Comment by rspauwen** [comment] 2023-03-15 09:41
Our problem appears to be fixed (not sure whether it's because of version 3, 4 or 5 :grin: ). Thanks anyway!

**Comment by devrnt** [comment] 2023-06-14 19:45
Re-opened!

**Comment by clayton-knapp** [comment] 2023-08-16 23:34
Hi thanks for reopening this ticket. We are also experiencing this problem at reclaim.ai

**Comment by devrnt** [comment] 2023-08-20 16:06
Please provide a minimal reproduction

**Comment by devrnt** [comment] 2024-06-13 20:02
Closing this again since no reproduction is provided

**Closed by devrnt** 2024-06-13 20:02 UTC
